export const theme = {
  colors: {
    surface: '#fbf9f9',
    surfaceDim: '#dbdad9',
    surfaceBright: '#fbf9f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f5f3f3',
    surfaceContainer: '#efeded',
    surfaceContainerHigh: '#e9e8e7',
    surfaceContainerHighest: '#e4e2e2',
    onSurface: '#1b1c1c',
    onSurfaceVariant: '#414942',
    inverseSurface: '#303031',
    inverseOnSurface: '#f2f0f0',
    outline: '#727972',
    outlineVariant: '#c1c8c0',
    surfaceTint: '#40674c',
    primary: '#3d644a',
    onPrimary: '#ffffff',
    primaryContainer: '#567d62',
    onPrimaryContainer: '#f6fff5',
    inversePrimary: '#a6d1b1',
    secondary: '#635e51',
    onSecondary: '#ffffff',
    secondaryContainer: '#eae2d1',
    onSecondaryContainer: '#696457',
    tertiary: '#5a5d58',
    onTertiary: '#ffffff',
    tertiaryContainer: '#727570',
    onTertiaryContainer: '#fbfdf6',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#c1edcc',
    primaryFixedDim: '#a6d1b1',
    onPrimaryFixed: '#00210f',
    onPrimaryFixedVariant: '#284e36',
    secondaryFixed: '#eae2d1',
    secondaryFixedDim: '#cdc6b6',
    onSecondaryFixed: '#1f1b11',
    onSecondaryFixedVariant: '#4b463a',
    tertiaryFixed: '#e1e3dc',
    tertiaryFixedDim: '#c5c7c1',
    onTertiaryFixed: '#191c18',
    onTertiaryFixedVariant: '#444843',
    background: '#fbf9f9',
    onBackground: '#1b1c1c',
    surfaceVariant: '#e4e2e2',
  },
  typography: {
    display: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 48,
      lineHeight: 57.6,
      letterSpacing: -0.96,
    },
    headlineLg: {
      fontFamily: 'Manrope_600SemiBold',
      fontSize: 32,
      lineHeight: 41.6,
    },
    headlineMd: {
      fontFamily: 'Manrope_500Medium',
      fontSize: 24,
      lineHeight: 33.6,
    },
    bodyLg: {
      fontFamily: 'Manrope_400Regular',
      fontSize: 18,
      lineHeight: 28.8,
    },
    bodyMd: {
      fontFamily: 'Manrope_400Regular',
      fontSize: 16,
      lineHeight: 25.6,
    },
    labelMd: {
      fontFamily: 'Manrope_500Medium',
      fontSize: 14,
      lineHeight: 16.8,
      letterSpacing: 0.14,
    },
  },
  rounded: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    unit: 4,
    xs: 8,
    sm: 16,
    md: 24,
    lg: 40,
    xl: 64,
    containerPadding: 24,
    gutter: 20,
  },
};
